### PR TITLE
Database table for waters

### PR DESCRIPTION
**Pull request by jnsdrtlf**
This pull request introduces a new model called `Water` along with some new features. We try to avoid using the Overpass API as much as possible by storing the geometry of most waters in the database itself.

Features:

- [x] New model called `Water`
- [x] Link measurements with waters
- [x] Differentiate between flowing water and stagnant water
- [x] Allow users to add new waters/rename existing (?)
- [x] Perform geo lookups using own database
- [x] Import functions to populate the database
- [x] Automatically check for missing waters when creating a new measurement

### CODE REVIEW

**Review by ax-sc — COMMENTED** [review]
The `map_options_url` tag is also used in the list of measurements: https://github.com/desklab/gcampus/blob/177409730373b45474463cb136fceffb5aae31a2/gcampus/core/templates/gcampuscore/components/measurement_list_item.html#L22

**Comment by ax-sc** [comment]
> Allow users to add new waters/rename existing (?)

How do you plan to implement adding new waters? Wouldn´t we need functions to let users define the geometry and meta data if the water is not found in OSM? I think it is a good idea to automatically add waters, which are not in our database, once they are requested. For renaming and adding new waters manually i would rather hint to improve OSM itself or make it easy to report this missing water to us, such that we could take care of it.

**Comment by jnsdrtlf** [comment]
Things that still have to be done:

- [ ] Fix tests
- [ ] Fix edit form

**Comment by ax-sc** [comment]
Nice work! 🎉 I created a few measurements and used the different options to select/add new waters (not sure if i have missed anything) and really liked the performance and the look of your changes, so this is definitely going into the right direction. There a just a few things i noticed:

- [ ] Water names are not displayed in the list of measurements and in the detail view (for both web and printed documents).
- [ ] The location marker in the detail view is missing.
- [ ] Selecting a point in the mapview does not trigger a popover.
- [ ] Should we sanitize the input for a custom water, such that it is impossible to select e.g. "standing water" and "river" at the same time? 
- [ ] Maybe we should add some parameter types and parameters to the fixture?

Let me know if i should help you with any of the points above.

**Comment by jnsdrtlf** [comment]
> Maybe we should add some parameter types and parameters to the fixture?

Oups, I have accidentally overwritten them. The fixture needs some more work anyways. Do you have time to do this? I usually make changes using GewässerCampus and the admin interface and then retrieve the entries using this command:
```shell
python manage.py dumpdata --exclude admin --exclude auth --exclude contenttypes --exclude sessions --format json -o test.json
```
I then copy the relevant information from `test.json` to `fixture.json`. You may sometimes need to edit the `pk` and relationship values.

> Should we sanitize the input for a custom water, such that it is impossible to select e.g. "standing water" and "river" at the same time?

I think this should be fine. If the flow type is left blank, it will be guessed from the water type (e.g. river is running water, pond is standing water). Nevertheless, I would still allow 'conflicting' water and flow types (and did this in the backend by design). Maybe somewhere out there there is a river that is not flowing 😄.

> Selecting a point in the mapview does not trigger a popover.

Jup, will fix this when merging with the popover commit that you already made.

<hl>


As for the other two points: Will fix them right-away (except for the list entry, as there are changes on the `develop` branch anyway).

**Comment by jnsdrtlf** [comment]
@ax-sc all done! Thanks for your suggestions! Can you re-review my changes?

As for the merge conflicts, I will manually resolve them when merging everything locally.

**Pull request merged**
