### PR TITLE
Improved Data Export

### PR DESCRIPTION
**Pull request by jnsdrtlf**
Addresses issue #78.

To implement the export views, a custom response class `MeasurementExportResponse` is introduced, which in turn is a subclass of `django.http.FileResponse`. Instead of streaming the contents of the files on-the-fly as in the previous approach, a temporary file is created and served. This enables the use of the `xlsxwriter` package, allowing detailed customisation of the XLSX file and its formatting.

### CODE REVIEW

**Comment by jnsdrtlf** [comment]
All done, feel free to add your reviews :)

**Comment by jnsdrtlf** [comment]
I am currently missing the individual rows of the structure index in the CSV export. Only the value of the index (including its validity) is included in the CSV export for now. Same for the XLSX export.

**Review by ax-sc — COMMENTED** [review]
Thanks, looks already really good to me! Just a few questions/suggestions:

1. I would prefer the `data_quality_warning` column to be empty for water quality indices in the csv, as it may be misleading if there is a `FALSE` when the `index_validity` is low.
2. What do you think of adding the `parameter_type__identifier` to the csv export? Maybe we can even use it to replace the current first column (type, currently translated)?
3. Should we add `water_type` to both the csv and the xlsx export?
4. Maybe we can add a field containing the `index__classification` combined with the `index__description`?
5. I think we don´t need the decimals of the `index_validity` in the xlsx export, it should be enough to use a two digit percentage formatted field.
6. Biological parameters shouldn´t have any decimals, as they are whole numbers (abundance counts).
7. Originally in #78 we had planned to use two separate csv files for indices and parameters, should we implement this only later?

**Comment by ax-sc** [comment]
As the `xlsx-streaming` package is no longer needed (right?), we should remove it from `requirements.txt`.

**Comment by jnsdrtlf** [comment]
Thanks for your feedback! I updated the code and added your suggestions :)

> I would prefer the data_quality_warning column to be empty for water quality indices in the csv, as it may be misleading if there is a FALSE when the index_validity is low.

❓ I disagree with you on this. Some indices (e.g. BACH) are calculated from the parameters of the measurement. If one of these parameters is off and the measurement has a `data_quality_warning`, you should be able to see it immediately, without having to iterate over all other parameters, find parameters of the same measurement, and see if they have a `data_quality_warning`. It makes it easier to just ignore all measurements with a `data_quality_warning` when performing data analysis.

> What do you think of adding the `parameter_type__identifier` to the csv export? Maybe we can even use it to replace the current first column (type, currently translated)?

✅ Great idea! I added the column. As we do not use the identifier in the front-end much, I would still include the full name (but move it to the end). Note that there is currently no translation when it comes to the parameter type. The names are in German in the database.

> Should we add `water_type` to both the csv and the xlsx export?

✅ Good idea, added it :)

> Maybe we can add a field containing the `index__classification` combined with the `index__description`?

❓ Unsure about this. They add a lot of data and can't be used e.g. for plotting.

> I think we don't need the decimals of the `index_validity` in the xlsx export, it should be enough to use a two digit percentage formatted field.

✅ Fixed. Used the wrong Excel number format.

> Biological parameters shouldn't have any decimals, as they are whole numbers (abundance counts).

❓ I agree, and was wondering how we want to address this. Are all biological parameters strictly integers?

> Originally in https://github.com/desklab/gcampus/issues/78 we had planned to use two separate csv files for indices and parameters, should we implement this only later?

❓ Do we need this? I saw it just after I finished the CSV export. Wouldn't be hard to implement.

**Comment by ax-sc** [comment]
left out the suggestions you already fixed, thanks for the update!

> > I would prefer the data_quality_warning column to be empty for water quality indices in the csv, as it may be misleading if there is a FALSE when the index_validity is low.
> 
> ❓ I disagree with you on this. Some indices (e.g. BACH) are calculated from the parameters of the measurement. If one of these parameters is off and the measurement has a `data_quality_warning`, you should be able to see it immediately, without having to iterate over all other parameters, find parameters of the same measurement, and see if they have a `data_quality_warning`. It makes it easier to just ignore all measurements with a `data_quality_warning` when performing data analysis.

Okay, good point, i thought this behaviour originates from using FALSE as a default (we have no indices with a warning in our fixture...). I definitely agree with your argumentation (we should then keep the value), I was just confused as we don´t have a direct `data_quality_warning` for indices (which may be the result of two parameters strongly indicating different water quality etc.). Should we rename the column to something like `parameter_quality_warning` in case we ever want to introduce the quality warning described before and would therefore need to differentiate between the two? This would help to avoid confusion with the `index_validity` as well.


> > Maybe we can add a field containing the `index__classification` combined with the `index__description`?
> 
> ❓ Unsure about this. They add a lot of data and can't be used e.g. for plotting.

Forgot to mention it, but i was only thinking of the xlsx export here. I feel like it´s not that easy to get a fast overview of the calculated indices (as each of them has a different range etc.) if we only display the numeric value.


> > Biological parameters shouldn't have any decimals, as they are whole numbers (abundance counts).
> 
> ❓ I agree, and was wondering how we want to address this. Are all biological parameters strictly integers?

Yes, all of them are currently integers and I do not know of any biological parameters we may want to implement in the future, which are not. 
 

> > Originally in #78 we had planned to use two separate csv files for indices and parameters, should we implement this only later?
> 
> ❓ Do we need this? I saw it just after I finished the CSV export. Wouldn't be hard to implement.

It might be easier to understand, but it´s not that important.

**Comment by jnsdrtlf** [comment]
I think renaming the `data_quality_warning` to `parameter_quality_warning` is a great idea. I would suggest doing this on the model level (i.e. renaming the database column) on the `main` branch once #85 is merged to avoid conflicts with the migrations (#85 adds a migration to the `core` app).

**Comment by jnsdrtlf** [comment]
> Forgot to mention it, but i was only thinking of the xlsx export here. I feel like it´s not that easy to get a fast overview of the calculated indices (as each of them has a different range etc.) if we only display the numeric value.

I agree, will add this to the xlsx export :)

**Comment by jnsdrtlf** [comment]
> Yes, all of them are currently integers and I do not know of any biological parameters we may want to implement in the future, which are not.

I'll look into it. Should be fairly easy to do this 👍🏽

**Comment by jnsdrtlf** [comment]
@ax-sc feel free to re-review or merge when you think the PR is ready :)

**Pull request merged**
